name: 'Setup Just'
description: 'Install the Just command runner'
runs:
  using: 'composite'
  steps:
    - name: Install just
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin
        echo "/usr/local/bin" >> $GITHUB_PATH
