name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-cache
    - uses: ./.github/actions/setup-just
    - name: Run check
      run: just check

  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-cache
    - uses: ./.github/actions/setup-just
    - name: Run build
      run: just build --verbose

  test:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-cache
    - uses: ./.github/actions/setup-just
    - name: Run test
      run: just test --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-cache
    - uses: ./.github/actions/setup-just
    - name: Run format
      run: just format --check
    - name: Run lint
      run: just lint
